const $=id=>document.getElementById(id);
const names=['Google Gemini','OpenRouter','Custom API'];
const state={prompts:['',''],defaults:['',''],prompt:0,output:'memo',method:'inline',busy:false,editing:false,outputs:{memo:'',transcript:''},stages:[['Google Gemini','gemini-3-flash-preview'],['Google Gemini','gemini-3-flash-preview']],settings:{}};
const example='<span class="example-tag">EXAMPLE MEMO</span><h1>Weekly team sync</h1><p class="meta">8 September 2026&nbsp;&nbsp; · &nbsp;&nbsp;3 participants</p><hr><h2>Summary</h2><p>The team reviewed progress on current projects, discussed upcoming milestones, and aligned on next steps. Overall, the project is on track, with a few risks to monitor and clear actions agreed for the coming weeks.</p><hr><h2>Key decisions</h2><ul><li>Proceed with the beta launch in October as planned.</li><li>Allocate additional resources to improve test coverage.</li></ul><hr><h2>Action items</h2><div class="task"><input type="checkbox" disabled><span class="task-name">Prepare beta launch communication plan.</span><span class="owner">Anna</span><span class="due">12 Sep 2026</span></div><div class="task"><input type="checkbox" disabled><span class="task-name">Follow up with design team on onboarding flow.</span><span class="owner">Juhan</span><span class="due">15 Sep 2026</span></div><div class="task"><input type="checkbox" disabled><span class="task-name">Set up monitoring for key metrics.</span><span class="owner">Liis</span><span class="due">19 Sep 2026</span></div>';
function icons(){lucide.createIcons();}
function status(text){$('status').textContent=text;}
async function api(method,...args){if(!window.pywebview){status('Open MemoMaker to use desktop controls');return null;}try{const r=await window.pywebview.api[method](...args);if(r?.error)throw Error(r.error);return r;}catch(e){status(e.message);$('settings-status').textContent=e.message;return null;}}
function render(){const text=state.outputs[state.output];$('edit').hidden=!text;$('copy').disabled=!text;$('export').disabled=!text;$('output-editor').hidden=!state.editing;$('preview').hidden=state.editing;if(state.editing){$('output-editor').value=text;return;}if(text){$('preview').innerHTML=state.output==='memo'?DOMPurify.sanitize(marked.parse(text)):'';if(state.output==='transcript'){$('preview').textContent=text;$('preview').style.whiteSpace='pre-wrap';}else $('preview').style.whiteSpace='normal';}else{$('preview').style.whiteSpace='normal';$('preview').innerHTML=state.output==='memo'?example:'<p class="meta">No transcript yet.</p>';}}
function saveEdit(){if(state.editing)state.outputs[state.output]=$('output-editor').value;state.editing=false;}
function busy(value){state.busy=value;['generate','load-output','source','drop-zone','clear-file'].forEach(id=>$(id).disabled=value);$('progress').hidden=!value;}
$('load-output').onclick=async()=>{if(state.busy)return;saveEdit();const kind=state.output;if(state.outputs[kind]&&!confirm('Replace the current '+kind+' in the workspace?'))return;const result=await api('load_output',kind);if(!result)return;window.receive(kind,result.text);if(kind==='transcript'){$('source').value='transcript';processing();}status('Loaded '+result.name);};
$('source').onchange=()=>{processing();if($('source').value==='transcript')document.querySelector('[data-output="transcript"]').click();};
$('save-prompts').onclick=async()=>{const profile=$('profile').value;const prompts=[...state.prompts];$('save-prompts').disabled=true;$('profile').disabled=true;try{const result=await api('save_prompts',profile,prompts);if(result){state.defaults=[...result];status('Saved both prompts to '+profile);}}finally{$('save-prompts').disabled=false;$('profile').disabled=false;}};
document.querySelectorAll('[data-output]').forEach(b=>b.addEventListener('click',()=>{$('load-output').title='Load '+b.dataset.output;}));
document.querySelectorAll('[data-output]').forEach(b=>b.onclick=()=>{saveEdit();state.output=b.dataset.output;document.querySelectorAll('[data-output]').forEach(x=>x.classList.toggle('active',x===b));render();});
document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{state.prompts[state.prompt]=$('prompt-editor').value;state.prompt=Number(b.dataset.prompt);$('prompt-editor').value=state.prompts[state.prompt];document.querySelectorAll('[data-prompt]').forEach(x=>x.classList.toggle('active',x===b));});
$('prompt-editor').oninput=()=>state.prompts[state.prompt]=$('prompt-editor').value;
$('reset').onclick=()=>{state.prompts=[...state.defaults];$('prompt-editor').value=state.prompts[state.prompt];};
document.querySelectorAll('[data-method]').forEach(b=>b.onclick=()=>{state.method=b.dataset.method;document.querySelectorAll('[data-method]').forEach(x=>x.classList.toggle('active',x===b));processing();});
function fileChosen(file){if(!file)return;$('selected-file').hidden=false;$('file-name').textContent=file.name;$('file-size').textContent=file.size;if($('source').value==='transcript')$('source').value='audio';processing();}
$('drop-zone').onclick=async()=>fileChosen(await api('browse'));
$('clear-file').onclick=async()=>{await api('clear_file');$('selected-file').hidden=true;};
const zone=$('drop-zone');zone.ondragover=e=>{e.preventDefault();zone.classList.add('drag');};zone.ondragleave=()=>zone.classList.remove('drag');zone.ondrop=e=>{e.preventDefault();zone.classList.remove('drag');};
$('profile').onchange=async()=>{const r=await api('profile',$('profile').value);if(r){state.prompts=[...r];state.defaults=[...r];$('prompt-editor').value=r[state.prompt];}};
$('settings-open').onclick=()=>{$('settings-status').textContent='';$('settings').showModal();};
$('settings-close').onclick=()=> $('settings').close();
function processing(){$('audio-limits-panel').hidden=$('source').value==='transcript';showAudioLimits($('audio-limits'),...state.stages[0],state.method);$('generate').innerHTML='<i data-lucide="sparkles"></i>'+($('source').value==='transcript-only'?'Generate transcript':'Generate memo');icons();const transcript=$('source').value==='transcript';const google=state.stages[0][0]==='Google Gemini';$('methods').hidden=!google||transcript;$('provider-summary').hidden=google&&!transcript;$('provider-summary').textContent=transcript?'Writing: '+state.stages[1].join(' / '):state.stages[0].join(' / ');}
function buildStages(){const host=$('stages');host.innerHTML='';state.stages.forEach((stage,i)=>{const row=document.createElement('section');row.className='stage';row.innerHTML='<h2>'+(i?'Writing model':'Transcription model')+'</h2><div class="stage-row"><select aria-label="Provider"></select><input aria-label="Model" list="models-'+i+'" placeholder="Model ID"><datalist id="models-'+i+'"></datalist><button type="button" class="icon-button" title="Refresh model list"><i data-lucide="refresh-cw"></i></button></div>';const select=row.querySelector('select'),input=row.querySelector('input');names.forEach(n=>select.add(new Option(n,n)));select.value=stage[0];input.value=stage[1];select.onchange=()=>{input.value=select.value==='Google Gemini'?'gemini-3-flash-preview':'';row.querySelector('datalist').innerHTML='';};row.querySelector('button').onclick=async()=>{const button=row.querySelector('button');button.disabled=true;$('settings-status').textContent='Loading models…';const r=await api('models',select.value,i===0,readSettings());if(r){const list=row.querySelector('datalist');list.innerHTML='';r.forEach(model=>list.append(new Option(model,model)));$('settings-status').textContent=r.length+' models loaded';}button.disabled=false;};if(i===0){const limits=document.createElement('div');limits.className='audio-limits';row.append(limits);const update=()=>showAudioLimits(limits,select.value,input.value.trim(),state.method);const change=select.onchange;select.onchange=()=>{change();update();};input.addEventListener('input',update);update();}host.append(row);});icons();}
function readSettings(){const result={};['GEMINI_API_KEY','OPENROUTER_API_KEY','CUSTOM_API_KEY','base_url','audio_mode'].forEach(k=>result[k]=$(k).value);return result;}
$('settings-form').onsubmit=async e=>{e.preventDefault();const stages=[...document.querySelectorAll('.stage')].map(r=>[r.querySelector('select').value,r.querySelector('input').value.trim()]);const s=readSettings();const r=await api('save_settings',s,$('remember').checked,stages);if(r){state.settings=s;state.stages=stages;processing();$('settings').close();status('API settings applied');}};
$('generate').onclick=async()=>{if(state.busy)return;saveEdit();const transcript=$('source').value==='transcript'?state.outputs.transcript:null;if(transcript!==null&&!transcript.trim()){status('Load a transcript in the Transcript tab first.');return;}busy(true);status('Starting…');const r=await api('generate',state.stages,[...state.prompts],state.method,transcript,$('source').value==='transcript-only');if(!r)busy(false);};
window.receive=(kind,value)=>{if(kind==='memo'||kind==='transcript'){state.outputs[kind]=value;state.output=kind;state.editing=false;$('load-output').title='Load '+kind;document.querySelectorAll('[data-output]').forEach(b=>b.classList.toggle('active',b.dataset.output===kind));render();}else if(kind==='done'){busy(false);status(value);}else if(kind==='status')status(value);if(kind!=='memo'&&kind!=='transcript')$('log').textContent+=value+'\n';};
$('edit').onclick=()=>{if(state.editing)saveEdit();else state.editing=true;render();$('edit').title=state.editing?'Save edits':'Edit output';};
$('copy').onclick=async()=>{saveEdit();render();if(await api('copy',state.outputs[state.output]))status('Copied');};
$('export').onclick=async()=>{saveEdit();render();if(await api('export',state.output,state.outputs[state.output]))status('Exported');};
$('activity-toggle').onclick=()=> $('activity').hidden=!$('activity').hidden;
$('activity-close').onclick=()=> $('activity').hidden=true;
$('preview').addEventListener('click',e=>{const link=e.target.closest('a');if(link){e.preventDefault();api('open_link',link.href);}});
window.addEventListener('pywebviewready',async()=>{const data=await api('initialize');if(!data)return;state.settings=data.settings;state.stages=data.stages;Object.entries(data.settings).forEach(([k,v])=>{if($(k))$(k).value=v;});data.profiles.forEach(p=>$('profile').add(new Option(p,p)));$('profile').value=data.profile;state.prompts=data.prompts;state.defaults=[...data.prompts];$('prompt-editor').value=state.prompts[0];buildStages();processing();});
buildStages();render();icons();
// Explicit visual QA fixture; never used by the desktop application.
if(new URLSearchParams(location.search).has('example')){fileChosen({name:'Team meeting.mp3',size:'16.4 MB'});$('profile').add(new Option('Estonian','ET'));$('prompt-editor').value='Identify each speaker and include timestamps.\n\nKeep the original meaning and wording.\n\nRemove filler words and repetitions.';}
